# Generated by Django 4.2 on 2023-05-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('planteamiento', models.CharField(max_length=200)),
                ('modulo', models.IntegerField(choices=[('', '-------------'), (1, 'Bosque'), (2, 'Laberinto'), (3, 'Recuperación')])),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id_opcion', models.IntegerField(primary_key=True, serialize=False)),
                ('inciso', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=200)),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preguntas.pregunta', verbose_name='pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Contestacion',
            fields=[
                ('id_contestacion', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_intento', models.IntegerField()),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.estudiante', verbose_name='usuario')),
                ('id_opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preguntas.pregunta', verbose_name='opcion')),
            ],
        ),
    ]
