# Generated by Django 4.2 on 2023-06-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestacion',
            name='tiempo_segundos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='fase',
            field=models.IntegerField(choices=[('', '-------------'), (1, 'Bosque'), (2, 'Laberinto'), (3, 'Recuperación')], null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='modulo',
            field=models.IntegerField(choices=[(5, '5'), (2, '2'), (1, '1'), ('', '-------------'), (4, '4'), (3, '3')]),
        ),
    ]
