# Generated by Django 4.2 on 2023-06-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0002_contestacion_tiempo_segundos_pregunta_fase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestacion',
            name='id_opcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preguntas.opcion', verbose_name='opcion'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='modulo',
            field=models.IntegerField(choices=[(5, '5'), (2, '2'), (3, '3'), (1, '1'), (4, '4'), ('', '-------------')]),
        ),
    ]
