# Generated by Django 4.2 on 2023-05-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantel',
            fields=[
                ('id_plantel', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_plantel', models.CharField(max_length=300)),
                ('domicilio', models.CharField(max_length=200)),
                ('numero_telefono', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.IntegerField(primary_key=True, serialize=False)),
                ('grado', models.IntegerField()),
                ('letra', models.CharField(max_length=1)),
                ('id_palntel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.plantel', verbose_name='plantel')),
            ],
        ),
    ]
