# Generated by Django 4.2 on 2023-06-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargo_plantel',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='encargo_plantel',
            name='plantel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.grupo', verbose_name='grupo'),
        ),
    ]
